apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-12T21:39:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
  resourceVersion: "173062"
  uid: 87f07f34-552a-44c4-886d-c59afed3270f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.52.3.178
  clusterIPs:
  - 10.52.3.178
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31870
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.238.2.255
